sqljdbc:
	url : http://download.microsoft.com/download/0/2/A/02AAE597-3865-456C-AE7F-613F99F850A8/sqljdbc_4.0.2206.100_enu.tar.gz
	archive : sqljdbc_4.tar.gz
sqoop:
	lib_dir : /usr/hdp/2.3.0.0-2557/sqoop/lib
home_dir : /root